#!/bin/python
a,b,c=map(int,raw_input().split())
while a!=0 or b!=0 or c!=0:
    if b-a==c-b:
        print "AP "+str(c+(b-a))

    else:
        print "GP "+str(c*(b/a))
    a,b,c=map(int,raw_input().split())
